apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: patch-test

commonLabels:
  app: patch-test

resources:
  - namespace.yaml
  - serviceaccounts/patch-operator.yaml
  - patches/dex-config.yaml
  - clusterroles/patch-operator.yaml
  - clusterrolebindings/patch-operator.yaml

secretGenerator:
  - name: dex-config
    files:
      - config=secrets/dex-config.yaml

configMapGenerator:
  - name: argocd-cm
    files:
      - configs/argocd-cm/resource.exclusions
      - configs/argocd-cm/dex.config

generatorOptions:
  disableNameSuffixHash: true
