apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patch-operator-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patch-operator-test
subjects:
  - kind: ServiceAccount
    name: patch-operator
    namespace: patch-test
