connectors:
- config:
    clientID: system:serviceaccount:openshift-gitops:openshift-gitops-argocd-dex-server
    clientSecret: ...a very secret string...
    groups: []
    insecureCA: true
    issuer: https://kubernetes.default.svc
    redirectURI: https://example.com
  id: openshift
  name: OpenShift
  type: openshift
